import React, { useState } from 'react'

import { Swiper, SwiperSlide } from 'swiper/react';
import { EffectCoverflow, Pagination } from 'swiper/modules';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';

import './carousel.scss'

import project_1 from '../../assets/anitrack.jpg'
import project_2 from '../../assets/iq.jpg'
import project_3 from '../../assets/travel.jpg'
import project_4 from '../../assets/projo1.jpg'
import project_5 from '../../assets/sunset.jpg'
import Popup from '../Popups/popup';

import anitrackHome from '../../assets/case2/Dashboard-dk.jpg'
import anitrackHealth from '../../assets/case2/Health-dk.jpg'
import anitrackStats from '../../assets/case2/Stats-dk.png'


const projectsData = [
    {
        image: project_1,
        detail: "Flutter Mobile App",
        title: "Anitrack",
        problem: "Farmers and ranchers who want to make data-driven decisions to improve their operations face a major challenge due to the absence of effective tracking systems in the agricultural sector. I took on a project to use LoRa technology to build a tracking system that seamlessly blends with the surroundings",
        goal: "To design user-centric solutions that empowers farmers and ranchers to make data-driven decisions to increase productivity and sustainability while monitoring their livestock and equipment effectively",
        process: "I used a user-centered design process to create a tracking system that empathizes with farmers and ranchers' needs, addresses pain points, seamlessly integrates into the natural environment, provides real-time insights and alerts, and empowers them to make data-driven decisions that improve productivity and sustainability.",
        thought: "To evoke a sense of harmony with nature, I used a color palette consisting of #23AD77 as the primary color, representing the lush greenery of the agricultural landscape, and #EAEAEC as the light theme background, symbolizing the vast open sky. For the dark theme background, I chose #1E1E20, which creates a sleek and modern look, complementing the clean typography and intuitive iconography.",
        challenge: "A significant challenge was presented by the complex and scattered data generated by sensors in the field. I overcame this by designing a user-friendly dashboard with clear data visualizations and intuitive navigation to ensure users could quickly and easily access relevant information.",
        image1: anitrackHome,
        image2: anitrackHealth, 
        image3: anitrackStats, 
    },
    {
        image: project_2,
        detail: "Website Redesign",
        title: "SoftIQ Technologies",
    },
    {
        image: project_3,
        detail: "Web Development",
        title: "Travel Agency",
    },
    {
        image: project_4,
        detail: "Chrome Extension",
        title: "ZenFlow",
    },
    {
        image: project_5,
        detail: "Chrome Extension",
        title: "ZenFlow",
    },
]

const ProjectCarousel = () => {
    const [showPopup, setShowPopup] = useState(false);
    const [selectedProject, setSelectedProject] = useState(null);

    const openPopup = (project) => {
        setSelectedProject(project);
        setShowPopup(true);
        setShowPopup ? console.log("openPopup function working" + project.title) : console.log("oops::" + project.title)
    };

    const closePopup = () => {
        setShowPopup(false);
        setSelectedProject(null);
    };
    return (
        <section className='project_container' id="portfolio">
            <h6>Portfolio</h6>
            <h2 className='h2'>My Projects</h2>
            <Swiper
                effect={'coverflow'}
                grabCursor={true}
                centeredSlides={true}
                slidesPerView={'auto'}
                coverflowEffect={{
                    rotate: 0,
                    stretch: 0,
                    depth: 100,
                    modifier: 2,
                    slideShadows: true,
                }}
                pagination={true}
                loop={true}
                modules={[EffectCoverflow, Pagination]}
                className="mySwiper"
            >
                {projectsData.map((project, index) => (
                    <SwiperSlide key={index}>
                        <div className="project_box" onClick={() => openPopup(project)}>
                            <img src={project.image} alt={`Project ${index}`} />
                            <div className='content'>
                                <p>{project.detail}</p>
                                <h6>{project.title}</h6>
                            </div>
                        </div>
                    </SwiperSlide>
                ))}
            </Swiper>
            <Popup trigger={showPopup} setTrigger={closePopup}>
                {selectedProject && (
                    <div className='project_popup'>
                        <h2>{selectedProject.title} Case Study</h2>
                        <p>{selectedProject.detail}</p>
                        <hr className="divider" />
                        <div className='design_images'>
                            <img src={selectedProject.image1} />
                            <img src={selectedProject.image2} />
                            <img src={selectedProject.image3} />
                        </div>
                        <hr className="divider" /> 
                        <h4>🤔Problem Statement</h4>
                        <p>{selectedProject.problem}</p>
                        <hr className="divider" />
                        <h4>🎯Goals</h4>
                        <p>{selectedProject.goal}</p>
                        <hr className="divider" />
                        <h4>🎨Design Process</h4>
                        <p>{selectedProject.process}</p>
                        <hr className="divider" />
                        <h4>💡Thought Process</h4>
                        <p>{selectedProject.thought}</p>
                        <hr className="divider" />
                        <h4>😤Challenges & Solutions</h4>
                        <p>{selectedProject.challenge}</p>
                        <hr className="divider" />
                        {/* Add other details or components as needed */}
                    </div>
                )}
            </Popup>
        </section>
    )
}

export default ProjectCarousel